CREATE SEQUENCE category_ref_seq
    INCREMENT 5
START 100;

CREATE TABLE CATEGORIES
(
    id           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ref          BIGINT UNIQUE,
    name         VARCHAR(100) UNIQUE NOT NULL,
    merchant_ref BIGINT              NOT NULL
);