CREATE SEQUENCE merchant_ref_seq
    INCREMENT 5
START 100;

CREATE TABLE MERCHANTS
(
    id   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ref BIGINT UNIQUE,
    name VARCHAR(100) UNIQUE NOT NULL,
    shop_name  VARCHAR(100) UNIQUE NOT NULL,
    contact_person  VARCHAR(100) NOT NULL,
    email  VARCHAR(100) UNIQUE NOT NULL,
    phone  VARCHAR(100),
    address  VARCHAR(100),
    status  VARCHAR(30) NOT NULL
);